### ISSUE TITLE
Confusion between DTO and Value Object

### ISSUE THREAD

**Issue by jonathangreco** [codeliner/php-ddd-cargo-sample#51]
Hi,

I just read some classes in this repository and I found some DTO object that are in fact, to me, value objects.

A DTO is for me, just as stupid data container which is used to transport data between layers and tiers..It shouldn't contains any logic, nor assertions (berberleri/assert)
A value object have some logic inside, and is immutable, it should not contains any getter or setter and just return one primitive.

You have in this repository a mix between DTO and value object.

Is this wanted ? Is it my understanding of DTO or Value Object that is wrong ?

**Comment by codeliner** [comment]
Hi,

DTOs were simple classes before this #47 by @pl-github 
I've merged the change because immutability is always a good thing, but this does not mean that you have to design your DTOs the same way ;)

> it should not contains any getter or setter and just return one primitive.

Value objects are compared by their value(s) instead of an identifier, see the [RouteSpecification](https://github.com/codeliner/php-ddd-cargo-sample/blob/master/CargoBackend/src/Model/Cargo/RouteSpecification.php#L66)
This does NOT mean that have to return ONE primitive.

**Comment by jonathangreco** [comment]
Ok thanks for the answer
